### PR TITLE
dontRename Option

### PR DESCRIPTION
**Pull request by deefour**
I had a need for this (see #74) and thought there might be interest from others.

### CODE REVIEW

**Comment by deefour** [comment]
The failure was there before my work; `master` is breaking, I think from all the code cleaning recently.

**Comment by smysnk** [comment]
Yeah sorry this is not your fault, I am doing a major rewrite of things.  I'll make sure to include your feature in the final product.

**Comment by smysnk** [comment]
Should have this out by Tuesday or Wednesday.

**Comment by smysnk** [comment]
Sorry due to substantial structural changes I couldn't accept PR; however, this should now be implemented in v0.8.0.

**Comment by deefour** [comment]
@smysnk I get it. I'm just thrilled the functionality is available. __Thanks!__ :beer:

**Pull request closed without merging**
