### PR TITLE
Don't update refs for files which aren't renamed (issue #131)

### PR DESCRIPTION
**Pull request by inian**

### CODE REVIEW

**Comment by smysnk** [comment]
Looks good, thanks!

**Comment by prannayb** [comment]
I have a problem with this change. Even though I'm not renaming a particular file, I do want to update it's reference. Since I'm using this for appCache generation, for files that are served though an API and are not static files, I cannot rename their source files. However, based on their source files I can supply different query params for cache busting. This was previously done by supplying the source file name pattern in dontRenameFiles, and then in the replacer for file types of compiled files, I replace their references from 
"Controller/Foo?page=welcome" 
to 
"Controller/Foo?hash=a654de7e&page=welcome?

As a workaround I'm having to supply a transformFilename function, which implements the dontRenameFile regEx exclusion.

**Comment by lewactwo** [comment]
Why is that reverted? May create another option for case above?

**Comment by peterlozano** [comment]
I posted a new fix on #175

**Pull request merged**
