### PR TITLE
Fix missing peer dependency

### PR DESCRIPTION
**Pull request by dpilafian**
Issue #206 
```
npm WARN gulp-jshint@2.1.0 requires a peer of jshint@2.x but none is installed.
You must install peer dependencies yourself.
```

### CODE REVIEW

**Comment by pioug** [comment]
Thanks @dpilafian! I'll remove the gulp tasks/plugins altogether instead. A couple of npm scripts would be enough 😛

**Comment by dpilafian** [comment]
Yep, and I had already removed `gulpfile.js` on my local fork.  However, it's good practice to clean up bugs before making improvements, so I submitted the bug fix first.  I also have a bunch of fixes ready to go from errors found by jshint.

The same thing happened with my pull request that you rejected to fix the `internalBinding` error.  I did that fix so I could upgrade to gulp 4.

Do you not want people to contribute to your project?

**Comment by pioug** [comment]
I am sorry for the lack of communication, I just want to take shortcuts since I don't want to spend time to follow migration paths.

I am really sorry for the time you have spent on it. However, I think it's also good practice to discuss issues **first** to decide whether they are worth solving.

**Comment by dpilafian** [comment]
Migration paths?  Huh?  You click merge, it's done.

Good luck with your project.  Bye.

**Pull request closed without merging**
